#!/usr/bin/env ruby
require "erb"
require "fileutils"

repo="sickp/alpine-redis"

redis_version = ARGV.first
case redis_version
when /\A4\.0-rc\d\z/
  tags = %w(4.0 4 beta)
  redis_archive = "#{redis_version}.tar.gz"
  redis_url = "https://github.com/antirez/redis/archive/#{redis_archive}"
when /\A3\.2\.\d+\z/
  tags = %w(3.2 3 stable latest)
  redis_archive = "redis-#{redis_version}.tar.gz"
  redis_url = "http://download.redis.io/releases/#{redis_archive}"
when /\A3\.0\.\d+\z/
  tags = %w(3.0 old)
  redis_archive = "redis-#{redis_version}.tar.gz"
  redis_url = "http://download.redis.io/releases/#{redis_archive}"
else
  puts "Usage: build <redis_version>"
  puts "  <redis_version> = 4.0-rc{x} | 3.2.x | 3.0.x"
  exit 1
end

root_dir = File.dirname(__FILE__)
template_dir = File.join(root_dir, "templates")

gosu_version = "1.10"
template = ERB.new(File.read(File.join(template_dir, "Dockerfile.erb")))
version_dir = File.join(root_dir, "versions", redis_version)
FileUtils.rm_rf(version_dir)
FileUtils.mkdir(version_dir)
FileUtils.cp_r(File.join(template_dir, "rootfs"), version_dir)
File.write(File.join(version_dir, "Dockerfile"), template.result(binding))

system("docker build -t #{repo}:#{redis_version} --pull #{version_dir}") || abort
puts "Built #{repo}:#{redis_version}"

tags.each do |tag|
  system("docker tag #{repo}:#{redis_version} #{repo}:#{tag}") || abort
  puts "Tagged #{repo}:#{tag}"
end
