#!/usr/bin/env ruby
repo="sickp/alpine-redis"

redis_version = ARGV.first
case redis_version
when /\A4\.0-rc\d\z/
  tags = %w(4.0 4 beta)
when /\A3\.2\.\d+\z/
  tags = %w(3.2 3 stable latest)
when /\A3\.0\.\d+\z/
  tags = %w(3.0 old)
else
  puts "Usage: push <redis_version>"
  puts "  <redis_version> = 4.0-rc{x} | 3.2.x | 3.0.x"
  exit 1
end

tags.unshift(redis_version)

tags.each do |tag|
  system("docker push #{repo}:#{tag}") || abort
  puts "Pushed #{repo}:#{tag}"
end
